[workspace]
members = [
  "service",
  "program-keccak-inclusion",
  "common",
  "blob-tool",
  "runner-keccak-inclusion",
  "sdk",
]
default-members = ["service"]
resolver = "2"

[workspace.package]
version = "0.1.11"
edition = "2021"
authors = ["Nuke <nuke-web3@proton.me>", "c-node <connor@s1nus.com>"]
license = "MIT"
homepage = "https://celestia.org"
repository = "https://github.com/celestiaorg/eq-service"

[workspace.dependencies]
eq-common = { path = "common", version = "0.1.11" }
eq-sdk = { path = "sdk", version = "0.1.11" }

anyhow = "1.0"
clap = "4.5"
celestia-types = "0.13"
celestia-rpc = "0.11"
nmt-rs = "0.2"
sp1-zkvm = { version = "5.1", features = ["verify"] }
sp1-sdk = { version = "5.1" }
sp1-build = { version = "5.1" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
tendermint-proto = "0.40"
tendermint = "0.40"
bincode = "1.3"
tokio = { version = "1.45", features = ["macros", "rt-multi-thread"] }
hex = "0.4"
serde_json = "1.0"
thiserror = "2.0"
sled = "0.34"
prost = "0.12.6"
tonic = { version = "0.11.0", default-features = false, features = ["codegen"] }
tonic-build = { version = "0.11.0", default-features = false }
env_logger = "0.11"
log = "0.4"
base64 = "0.22"
jsonrpsee = "0.25"
prometheus-client = "0.23"
hyper = "1.6"
hyper-util = "0.1"
http-body-util = "0.1"

sha3 = "=0.10.8"
[patch.crates-io]
sha3 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", branch = "patch-sha3-v0.10.8" }
sha2-v0-9-9 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-v0.9.9" }
sha2-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-v0.10.8" }
# Internal dependency for alloy, used in sp1 SDK
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", branch = "patch-v2.0.2" }
