[package]
name = "eq-service"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
eq-common = {path = "../common"}
eq-sdk = {path = "../sdk"}
serde = { workspace = true, features = ["derive"] }
bincode = {workspace = true}
celestia-types = {workspace = true}
celestia-rpc = {workspace = true}
tokio = {workspace = true}
tonic = {workspace = true, features = ["transport"]}
sled = {workspace = true}
sp1-sdk = {workspace=true}
env_logger = {workspace=true}
log = {workspace=true}
hex = {workspace=true}
base64 = {workspace = true}
jsonrpsee = {workspace=true}
sha3 = {workspace=true}
