[package]
name = "eq_service"
version = "0.1.0"
edition = "2021"

[dependencies]
eq-common = {path = "../common"}
serde = { workspace = true, features = ["derive"] }
bincode = {workspace = true}
celestia-types = {workspace = true}
celestia-rpc = {workspace = true}
tokio = {workspace = true}
tonic = {workspace = true, features = ["transport"]}
sled = {workspace = true}
sp1-sdk = {workspace=true}
env_logger = {workspace=true}
log = {workspace=true}
base64 = {workspace = true}
jsonrpsee = {workspace=true}
