[package]
name = "eq-program-keccak-inclusion"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
eq-common = {path = "../common", default-features = false}
sp1-zkvm = {workspace = true}
celestia-types = {workspace = true}
nmt-rs = {workspace = true}
tendermint = {workspace = true}
tendermint-proto = {workspace = true}
sha3 = {workspace = true}
alloy = { workspace = true, default-features = false, features = ["sol-types"] }
