[package]
name = "runner-keccak-inclusion"
edition.workspace = true
version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[dependencies]
sp1-sdk.workspace = true
eq-common.workspace = true
serde_json.workspace = true
