[package]
name = "runner-keccak-inclusion"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-sdk = {workspace = true}
eq-common = {path = "../common"}
serde_json = {workspace = true}
