[package]
name = "runner-keccak-inclusion"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
sp1-sdk = {workspace = true}
eq-common = {path = "../common"}
serde_json = {workspace = true}
